CREATE DATABASE IF NOT EXISTS ekipe CHARACTER SET utf8mb4;
USE ekipe;

CREATE TABLE IF NOT EXISTS teams (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    members TEXT NOT NULL,
    score INT NOT NULL
);